// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqhSqwu0VNwAHTGnNL5WPSKlG9HEDd6w',
    appId: '1:383936808056:web:b38d9fd3b0daa2a330598d',
    messagingSenderId: '383936808056',
    projectId: 'iwipe-4d9bb',
    authDomain: 'iwipe-4d9bb.firebaseapp.com',
    storageBucket: 'iwipe-4d9bb.appspot.com',
    measurementId: 'G-657D30HQ8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlBmNwVBlaPbCSXvGFkF2SXgHVJa_hkE',
    appId: '1:383936808056:android:cb025f6189f3333330598d',
    messagingSenderId: '383936808056',
    projectId: 'iwipe-4d9bb',
    storageBucket: 'iwipe-4d9bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPIeR1_WCTPcNAI4j7JRrKQgx73vBmUiY',
    appId: '1:383936808056:ios:139c901ff0ada8d430598d',
    messagingSenderId: '383936808056',
    projectId: 'iwipe-4d9bb',
    storageBucket: 'iwipe-4d9bb.appspot.com',
    iosBundleId: 'com.iwipe.iwipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPIeR1_WCTPcNAI4j7JRrKQgx73vBmUiY',
    appId: '1:383936808056:ios:d54a7fc55bd7433d30598d',
    messagingSenderId: '383936808056',
    projectId: 'iwipe-4d9bb',
    storageBucket: 'iwipe-4d9bb.appspot.com',
    iosBundleId: 'com.iwipe.iwipe.RunnerTests',
  );
}
