// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTJsWp32VQcE4O0BYfOahKezlqDxq3u8',
    appId: '1:927628137875:web:16aabfc7613f8e4e928466',
    messagingSenderId: '927628137875',
    projectId: 'iwipe-40df6',
    authDomain: 'iwipe-40df6.firebaseapp.com',
    storageBucket: 'iwipe-40df6.appspot.com',
    measurementId: 'G-FZY45JFMMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyu0qJ9NQz9HkzoPsrBwK7TtCXLMaavQ',
    appId: '1:927628137875:android:b789789ac8d6e1c9928466',
    messagingSenderId: '927628137875',
    projectId: 'iwipe-40df6',
    storageBucket: 'iwipe-40df6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbRspWWdfsGH2DjHoEhYkOOUClqTT8v58',
    appId: '1:927628137875:ios:97b22cf77c6fa1fc928466',
    messagingSenderId: '927628137875',
    projectId: 'iwipe-40df6',
    storageBucket: 'iwipe-40df6.appspot.com',
    iosClientId: '927628137875-pcl6l5rvut0uenvj0nd38m9o9sr2drrf.apps.googleusercontent.com',
    iosBundleId: 'com.iwipe.iwipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbRspWWdfsGH2DjHoEhYkOOUClqTT8v58',
    appId: '1:927628137875:ios:f11ba6592a876e2a928466',
    messagingSenderId: '927628137875',
    projectId: 'iwipe-40df6',
    storageBucket: 'iwipe-40df6.appspot.com',
    iosClientId: '927628137875-p6aesl5eo93c2f7uu53uid4p8cf9rihk.apps.googleusercontent.com',
    iosBundleId: 'com.iwipe.iwipe.RunnerTests',
  );
}
